title: Chirra Thomas Portfolio
description: Benvenuti! Qui potete trovare alcuni dei programmi che ho creato.
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
github:
  zip_url: http://tomciuc.github.io/Download/RecursiveDirectory.zip


