title: Chirra Thomas Portfolio
description: Di seguito una lista dei miei lavori
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
github:
  zip_url: http://tomciuc.github.io/Download/RecursiveDirectory.zip


